# Generated by Django 3.1.7 on 2021-05-23 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hero',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_1', models.CharField(max_length=250)),
                ('text_2', models.CharField(max_length=250)),
                ('text_3', models.CharField(max_length=250)),
            ],
        ),
    ]
