# Generated by Django 3.1.7 on 2021-05-23 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0002_auto_20210523_2303'),
    ]

    operations = [
        migrations.AddField(
            model_name='herotext',
            name='lang',
            field=models.CharField(default='EN', max_length=2),
        ),
    ]
