# Generated by Django 3.1.7 on 2021-05-24 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0007_project'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Project',
        ),
    ]
