# Generated by Django 3.1.7 on 2021-05-24 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0009_project'),
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('open_button', models.CharField(max_length=50)),
                ('close_botton', models.CharField(max_length=50)),
                ('home_button', models.CharField(max_length=50)),
                ('products_button', models.CharField(max_length=50)),
                ('projects_button', models.CharField(max_length=50)),
                ('about_us_button', models.CharField(max_length=50)),
                ('contact_button', models.CharField(max_length=50)),
                ('lang', models.CharField(default='EN', max_length=2)),
            ],
        ),
        migrations.AddField(
            model_name='herotext',
            name='button_1',
            field=models.CharField(default='Our products', max_length=250),
        ),
        migrations.AddField(
            model_name='herotext',
            name='button_2',
            field=models.CharField(default='Get in touch', max_length=250),
        ),
    ]
