# Generated by Django 3.1.7 on 2021-05-24 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0010_auto_20210524_1017'),
    ]

    operations = [
        migrations.RenameField(
            model_name='menu',
            old_name='close_botton',
            new_name='close_button',
        ),
    ]
