# Generated by Django 3.1.7 on 2021-05-24 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0013_partnertext'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactText',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('subtitle', models.CharField(max_length=250)),
                ('name_field', models.CharField(max_length=50)),
                ('email_field', models.CharField(max_length=50)),
                ('message_field', models.CharField(max_length=50)),
                ('lang', models.CharField(default='EN', max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='ProductText',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('subtitle', models.CharField(max_length=250)),
                ('lang', models.CharField(default='EN', max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='ProjectText',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('subtitle', models.CharField(max_length=250)),
                ('lang', models.CharField(default='EN', max_length=2)),
            ],
        ),
    ]
