# Generated by Django 3.1.7 on 2021-05-24 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0014_contacttext_producttext_projecttext'),
    ]

    operations = [
        migrations.CreateModel(
            name='FooterText',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('copyright', models.CharField(max_length=250)),
                ('description', models.TextField()),
                ('lang', models.CharField(default='EN', max_length=2)),
            ],
        ),
    ]
