# Generated by Django 3.1.7 on 2021-05-24 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0015_footertext'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('category', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('price', models.CharField(max_length=30)),
                ('name_az', models.CharField(max_length=200)),
                ('category_az', models.CharField(max_length=200)),
                ('description_az', models.TextField()),
                ('price_az', models.CharField(max_length=30)),
                ('name_ru', models.CharField(max_length=200)),
                ('category_ru', models.CharField(max_length=200)),
                ('description_ru', models.TextField()),
                ('price_ru', models.CharField(max_length=30)),
                ('name_tr', models.CharField(max_length=200)),
                ('category_tr', models.CharField(max_length=200)),
                ('description_tr', models.TextField()),
                ('price_tr', models.CharField(max_length=30)),
                ('image', models.ImageField(upload_to='projects/')),
            ],
        ),
    ]
